namespace SeguraChain_Desktop_Wallet.Enum
{
    public enum ClassEnumTransactionHistoryColumnType
    {
        TRANSACTION_HISTORY_COLUMN_TRANSACTION_DATE = 0,
        TRANSACTION_HISTORY_COLUMN_TRANSACTION_TYPE = 1,
        TRANSACTION_HISTORY_COLUMN_TRANSACTION_WALLET_ADDRESS = 2,
        TRANSACTION_HISTORY_COLUMN_TRANSACTION_HASH = 3,
        TRANSACTION_HISTORY_COLUMN_TRANSACTION_AMOUNT = 4,
    }
}
