namespace SeguraChain_Lib.Blockchain.Sovereign.Enum
{
    public enum ClassSovereignEnumUpdateCheckStatus
    {
        #region About the update content to check.

        EMPTY_SOVEREIGN_UPDATE_OBJECT = 0,
        EMPTY_SOVEREIGN_UPDATE_CONTENT = 1,
        EMPTY_SOVEREIGN_UPDATE_HASH = 2,
        EMPTY_SOVEREIGN_UPDATE_SIGNATURE = 3,
        EMPTY_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS = 4,
        INVALID_SOVEREIGN_UPDATE_TIMESTAMP = 5,
        INVALID_SOVEREING_UPDATE_TYPE = 6,
        INVALID_SOVEREIGN_UPDATE_HASH_FORMAT = 7,
        INVALID_SOVEREIGN_UPDATE_SIGNATURE_FORMAT = 8,
        INVALID_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS_LENGTH = 9,
        INVALID_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS_BASE58_FORMAT = 10,
        INVALID_SOVEREIGN_UPDATE_HASH_ALREADY_LISTED = 11,

        #endregion

        #region About the validity of the update to check.

        INVALID_SOVEREIGN_UPDATE_HASH = 12,
        INVALID_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS = 13,
        INVALID_SOVEREIGN_UPDATE_SIGNATURE = 14,

        #endregion

        #region About the update order content to check and to use if valid.

        // Seed node rank update.
        EMPTY_SOVEREIGN_UPDATE_SEED_NODE_NUMERIC_PUBLIC_KEY_CONTENT = 15,
        INVALID_SOVEREIGN_UPDATE_SEED_NODE_NUMERIC_PUBLIC_KEY = 16,
        EMPTY_SOVEREIGN_UPDATE_SEED_NODE_MAX_RANK_DELAY_CONTENT = 17,
        INVALID_SOVEREIGN_UPDATE_SEED_NODE_MAX_RANK_DELAY = 18,

        // Wallet Dev informations update.
        EMPTY_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS_CONTENT = 19,
        INVALID_SOVEREIGN_UPDATE_DEV_WALLET_ADDRESS_CONTENT = 20,
        EMPTY_SOVEREIGN_UPDATE_DEV_PUBLIC_KEY_CONTENT = 21,
        INVALID_SOVEREIGN_UPDATE_DEV_PUBLIC_KEY_CONTENT = 22,

        // Mining Anti IA informations update.
        EMPTY_SOVEREIGN_UPDATE_MINING_POW_SETTING = 23,
        INVALID_SOVEREIGN_UPDATE_MINING_POWAC_SETTING_CONTENT = 24,

        #endregion

        VALID_SOVEREIGN_UPDATE = 27,
    }
}
