namespace SeguraChain_Lib.Blockchain.Transaction.Enum
{
    public class ClassTransactionSplitDataConfig
    {
        public const string TransactionSplitDataCharacterSeparator = "|";
    }


    public enum ClassTransactionEnumSplitData
    {
        INDEX_BLOCK_TRANSACTION_TOTAL_CONFIRMATION = 0,
        INDEX_BLOCK_TRANSACTION_STATUS = 1,
        INDEX_BLOCK_TRANSACTION_INVALID_REMOVE_TIMESTAMP = 2,
        INDEX_TRANSACTION_TYPE = 3,
        INDEX_TRANSACTION_BLOCK_HEIGHT = 4,
        INDEX_TRANSACTION_BLOCK_HEIGHT_CONFIRMATION_TARGET = 5,
        INDEX_TRANSACTION_HASH = 6,
        INDEX_TRANSACTION_AMOUNT = 7,
        INDEX_TRANSACTION_FEE = 8,
        INDEX_TRANSACTION_WALLET_ADDRESS_RECEIVER = 9,
        INDEX_TRANSACTION_PAYMENT_ID = 10,
        INDEX_TRANSACTION_VERSION = 11,
        INDEX_TRANSACTION_TIMESTAMP_SEND = 12,
        INDEX_TRANSACTION_WALLET_ADDRESS_SENDER = 13,
        INDEX_TRANSACTION_PUBLIC_KEY_SENDER = 14,
        INDEX_TRANSACTION_SIGNATURE_SENDER = 15,
        INDEX_TRANSACTION_PUBLIC_KEY_RECEIVER = 16,
        INDEX_TRANSACTION_SIGNATURE_RECEIVER = 17,
        INDEX_TRANSACTION_BLOCK_HASH = 18,
        INDEX_TRANSACTION_HASH_BLOCK_REWARD = 19,
        INDEX_TRANSACTION_SPEND_STATUS = 20,
        INDEX_TRANSACTION_SOURCE_LIST = 21,
        INDEX_TRANSACTION_BIG_SIGNATURE_SENDER = 22,
        INDEX_TRANSACTION_BIG_SIGNATURE_RECEIVER = 23,
        INDEX_TRANSACTION_TOTAL_SPEND = 24,
        INDEX_TRANSACTION_BLOCK_HEIGHT_INSERT = 25,
        INDEX_TRANSACTION_BLOCK_HEIGHT_TARGET = 26,
        INDEX_TRANSACTION_TIMESTAMP_BLOCK_HEIGHT_CREATE = 27,
        INDEX_TRANSACTION_INVALID_TRANSACTION_STATUS = 28,
        INDEX_TRANSACTION_IP = 29
    }
}
