namespace SeguraChain_Lib.Blockchain.Transaction.Enum
{
    public enum ClassTransactionEnumStatus
    {
        EMPTY_TRANSACTION = 0,
        INVALID_WALLET_ADDRESS_SENDER = 1,
        INVALID_WALLET_ADDRESS_RECEIVER = 2,
        INVALID_WALLET_PUBLIC_KEY = 3,
        INVALID_WALLET_ADDRESS_SENDER_FROM_PUBLIC_KEY = 4,
        INVALID_WALLET_ADDRESS_RECEIVER_FROM_PUBLIC_KEY = 5,
        INVALID_TRANSACTION_HASH = 6,
        INVALID_TRANSACTION_NULL_HASH = 7,
        INVALID_TRANSACTION_FORMAT_HASH = 8,
        INVALID_TRANSACTION_SIGNATURE = 9,
        INVALID_TRANSACTION_FEE = 10,
        INVALID_TRANSACTION_AMOUNT = 11,
        INVALID_BLOCK_HEIGHT = 12,
        INVALID_TRANSACTION_TYPE = 13,
        INVALID_TRANSACTION_BLOCK_AMOUNT = 14,
        INVALID_TRANSACTION_DEV_FEE_AMOUNT = 15,
        EMPTY_TRANSACTION_SOURCE_LIST = 16,
        DUPLICATE_TRANSACTION_HASH = 17,
        NOT_ENOUGHT_AMOUNT = 18,
        INVALID_BLOCK_WALLET_ADDRESS_WINNER = 19,
        BLOCK_HEIGHT_LOCKED = 20,
        INVALID_BLOCK_DEV_FEE_WALLET_ADDRESS_RECEIVER = 21,
        INVALID_BLOCK_HEIGHT_TARGET_CONFIRMATION = 22,
        INVALID_BLOCK_REWARD_SENDER_NAME = 23,
        INVALID_PAYMENT_ID = 24,
        INVALID_TRANSACTION_VERSION = 25,
        SAME_WALLET_ADDRESS = 26,
        INVALID_TRANSACTION_SOURCE_LIST = 27,
        NOT_ENOUGH_PEER_VOTE = 28,
        INVALID_TRANSACTION_FROM_VOTE = 29,
        VALID_TRANSACTION = 30,
        NOT_ENOUGH_BROADCASTED = 31,
    }

}
